//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public string PatientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int NacionalityID { get; set; }
        public string Diseases { get; set; }
        public string PhoneNumber { get; set; }
        public int BloodTypeID { get; set; }
    
        public virtual BloodType BloodType { get; set; }
        public virtual Nationality Nationality { get; set; }
    }
}
